title: "Manmadharao Patibandla"
logo: "Manmadh_cover_pic.jpg" # Ensure this is correct
description: "Java Full-Stack Developer"
###

show_downloads: true

##
##
theme: jekyll-theme-minimal

##
##
include: ["style.css"]
