title: "Manmadharao Patibandla"
logo: "Manmadharao.Patibandla.jpg" # Ensure this is correct
description: "Java Full-Stack Developer"

show_downloads: true

theme: jekyll-theme-minimal

include: ["style.css"]
